configuration for a subject prefix for email
fractaledmind/solid_errors pull request #66
Opened 2024-10-11 10:18 UTC by francescob

Added an option to add a subject prefix to the emails sent by solid_errors. Useful when you have multiple apps/environments using solid errors and what to easily filter the email received

2024-10-11 18:30 UTC, fractaledmind requested changes
I like the idea, just one small change needed

2024-10-11 18:30 UTC, fractaledmind commented on app/mailers/solid_errors/error_mailer.rb
> +        subject: "#{SolidErrors.subject_prefix} #{@error.severity_emoji} #{@error.exception_class}",
Handle an empty prefix

2024-10-14 08:38 UTC, francescob commented
Ok, now the empty prefix is handled.
i also have another idea that fits in the way we use solid_errors:
Make subject_prefix enabled by default, with a value of 
`[#{Rails.application.name.upcase][#Rails.application.env.upcase]`.
Disable it with config.solid_errors.subject_prefix = "" or override it with your own custom string
What do you think about that?

2024-10-22 17:21 UTC, fractaledmind approved these changes
LGTM

2024-10-22 17:21 UTC, fractaledmind commented
> Ok, now the empty prefix is handled. i also have another idea that fits in the way we use solid_errors: Make subject_prefix enabled by default, with a value of `[#{Rails.application.name.upcase][#Rails.application.env.upcase]`. Disable it with config.solid_errors.subject_prefix = "" or override it with your own custom string What do you think about that?

Making this the default would be a breaking change. I would rather introduce such a change slowly. So, let's start by providing that as the example in the README for this feature.

2024-10-23 08:11 UTC, francescob commented
Ok i've renamed the option for conformity with other email settings and updated the README

2024-10-23 14:16 UTC, fractaledmind commented on README.md
> +* `email_subject_prefix` - The subject prefix to use for email notifications. See [Email notifications](#email-notifications) for more information.
Still missing the newline before the next section title

2024-10-23 16:25 UTC, fractaledmind approved these changes
Lovely! Thank you for this

2024-10-23 16:25 UTC, merged